import { getRandomInt } from './utils';

const backgrounds = [
  'Acolyte',
  'Anthropologist',
  'Archaeologist',
  'Charlatan',
  'CityWatch / Investigator',
  'Clan Crafter',
  'Cloistered Scholar',
  'Courtier',
  'Criminal / Spy',
  'Entertainer',
  'Faceless',
  'Faction Agent',
  'Far Traveler',
  'Fisher',
  'Folk Hero',
  'Gladiator',
  'Guild Artisan / Guild Merchant',
  'Haunted One',
  'Hermit',
  'Inheritor',
  'Knight',
  'Knight of the Order',
  'Marine',
  'Mercenary Veteran',
  'Noble',
  'Outlander',
  'Pirate',
  'Sage',
  'Sailor',
  'Shipwright',
  'Smuggler',
  'Soldier',
  'Urban Bounty Hunter',
  'Urchin',
  'Uthgardt Tribe Member',
  'WaterdhavianNoble',
];

export const getBG = () => backgrounds[getRandomInt(backgrounds.length)];
