import { PHB, XGE, SCG } from './sources';
import { getRandomInt } from './utils';

const mainClasses = [
  { mainClass: 'Barbarian', subclass: 'Ancestral Guardian', book: XGE },
  { mainClass: 'Barbarian', subclass: 'Battlerager', book: SCG, race: 'Dwarf' },
  { mainClass: 'Barbarian', subclass: 'Berzerker', book: PHB },
  { mainClass: 'Barbarian', subclass: 'Storm Herald', book: XGE },
  { mainClass: 'Barbarian', subclass: 'Totem Warrior', book: PHB },
  { mainClass: 'Barbarian', subclass: 'Zealot', book: XGE },
  { mainClass: 'Bard', subclass: 'College of Glamour', book: XGE },
  { mainClass: 'Bard', subclass: 'College of Lore', book: PHB },
  { mainClass: 'Bard', subclass: 'College of Swords', book: XGE },
  { mainClass: 'Bard', subclass: 'College of Valor', book: PHB },
  { mainClass: 'Bard', subclass: 'College of Whispers', book: XGE },
  { mainClass: 'Cleric', subclass: 'Arcana Domain', book: SCG },
  { mainClass: 'Cleric', subclass: 'Forge Domain', book: XGE },
  { mainClass: 'Cleric', subclass: 'Grave Domain', book: XGE },
  { mainClass: 'Cleric', subclass: 'Knowledge Domain', book: PHB },
  { mainClass: 'Cleric', subclass: 'Life Domain', book: PHB },
  { mainClass: 'Cleric', subclass: 'Light Domain', book: PHB },
  { mainClass: 'Cleric', subclass: 'Nature Domain', book: PHB },
  { mainClass: 'Cleric', subclass: 'Order Domain', book: XGE },
  { mainClass: 'Cleric', subclass: 'Tempest Domain', book: PHB },
  { mainClass: 'Cleric', subclass: 'Trickery Domain', book: PHB },
  { mainClass: 'Cleric', subclass: 'War Domain', book: PHB },
  { mainClass: 'Druid', subclass: 'Circle of Dreams', book: XGE },
  { mainClass: 'Druid', subclass: 'Circle of the Moon', book: PHB },
  { mainClass: 'Druid', subclass: 'Circle of the Land', book: PHB },
  { mainClass: 'Druid', subclass: 'Circle of the Shepherd', book: XGE },
  { mainClass: 'Fighter', subclass: 'Arcane Archer', book: XGE },
  { mainClass: 'Fighter', subclass: 'Banneret', book: SCG },
  { mainClass: 'Fighter', subclass: 'Battlemaster', book: PHB },
  { mainClass: 'Fighter', subclass: 'Cavalier', book: XGE },
  { mainClass: 'Fighter', subclass: 'Champion', book: PHB },
  { mainClass: 'Fighter', subclass: 'Eldritch Knight', book: PHB },
  { mainClass: 'Fighter', subclass: 'Samurai', book: XGE },
  { mainClass: 'Monk', subclass: 'Way of the Drunken Master', book: XGE },
  { mainClass: 'Monk', subclass: 'Way of the Four Elements', book: PHB },
  { mainClass: 'Monk', subclass: 'Way of the Kensei', book: XGE },
  { mainClass: 'Monk', subclass: 'Way of the Long Death', book: SCG },
  { mainClass: 'Monk', subclass: 'Way of the Open Hand', book: PHB },
  { mainClass: 'Monk', subclass: 'Way of the Shadow', book: XGE },
  { mainClass: 'Monk', subclass: 'Way of the Sun Soul', book: SCG },
  { mainClass: 'Paladin', subclass: 'Oath of the Ancients', book: PHB },
  { mainClass: 'Paladin', subclass: 'Oath of Conquest', book: XGE },
  { mainClass: 'Paladin', subclass: 'Oath of the Crown', book: SCG },
  { mainClass: 'Paladin', subclass: 'Oath of Devotion', book: XGE },
  { mainClass: 'Paladin', subclass: 'Oath of Vengeance', book: PHB },
  { mainClass: 'Ranger', subclass: 'Beast Master', book: PHB },
  { mainClass: 'Ranger', subclass: 'Gloom Stalker', book: XGE },
  { mainClass: 'Ranger', subclass: 'Horizon Walker', book: XGE },
  { mainClass: 'Ranger', subclass: 'Hunter', book: PHB },
  { mainClass: 'Ranger', subclass: 'Monster Slayer', book: XGE },
  { mainClass: 'Rogue', subclass: 'Arcane Trickster', book: PHB },
  { mainClass: 'Rogue', subclass: 'Assassin', book: PHB },
  { mainClass: 'Rogue', subclass: 'Inquisitive', book: XGE },
  { mainClass: 'Rogue', subclass: 'Mastermind', book: SCG },
  { mainClass: 'Rogue', subclass: 'Scout', book: XGE },
  { mainClass: 'Rogue', subclass: 'Swashbuckler', book: SCG },
  { mainClass: 'Rogue', subclass: 'Thief', book: PHB },
  { mainClass: 'Sorcerer', subclass: 'Draconic Bloodline', book: PHB },
  { mainClass: 'Sorcerer', subclass: 'Divine Soul', book: XGE },
  { mainClass: 'Sorcerer', subclass: 'Shadow', book: XGE },
  { mainClass: 'Sorcerer', subclass: 'Storm', book: SCG },
  { mainClass: 'Sorcerer', subclass: 'Wild Magic', book: PHB },
  { mainClass: 'Warlock', subclass: 'Archfey', book: PHB },
  { mainClass: 'Warlock', subclass: 'Celestial', book: XGE },
  { mainClass: 'Warlock', subclass: 'Fiend', book: PHB },
  { mainClass: 'Warlock', subclass: 'Great Old One', book: PHB },
  { mainClass: 'Warlock', subclass: 'Hexblade', book: XGE },
  { mainClass: 'Warlock', subclass: 'Undying', book: SCG },
  { mainClass: 'Wizard', subclass: 'School of Abjuration', book: PHB },
  { mainClass: 'Wizard', subclass: 'Bladesinger', book: SCG, race: 'Elf' },
  { mainClass: 'Wizard', subclass: 'School of Conjuration', book: PHB },
  { mainClass: 'Wizard', subclass: 'School of Divination', book: PHB },
  { mainClass: 'Wizard', subclass: 'School of Enchantment', book: PHB },
  { mainClass: 'Wizard', subclass: 'School of Evocation', book: PHB },
  { mainClass: 'Wizard', subclass: 'School of Illusion', book: PHB },
  { mainClass: 'Wizard', subclass: 'School of Necromancy', book: PHB },
  { mainClass: 'Wizard', subclass: 'School of Transmutation', book: PHB },
  { mainClass: 'Wizard', subclass: 'War Magic', book: XGE },
];

export const getClass = ({ race: raceUsed, book: bookUsed }) => {
  let validClasses = mainClasses.filter(({ race }) => !(race && race !== raceUsed));

  if (bookUsed) {
    validClasses = validClasses.filter(({ book }) => book === bookUsed || !book);
  }

  const { mainClass, subclass, book } = validClasses[getRandomInt(validClasses.length)];
  return {
    mainClass: `${subclass ? subclass + ' ': ''}${mainClass}`,
    book: book || bookUsed,
  };
}
