import { PHB, EE, VGM, XGE, LOC, SCG, MTF } from './sources';
import { getRandomInt } from './utils';

const races = [
  { race: 'Dragonborn', book: PHB },
  { race: 'Dwarf', subrace: 'Hill', book: PHB },
  { race: 'Dwarf', subrace: 'Mountain', book: PHB },
  { race: 'Dwarf', subrace: 'Gray', book: SCG },
  { race: 'Elf', subrace: 'High', book: PHB },
  { race: 'Elf', subrace: 'Wood', book: PHB },
  { race: 'Elf', subrace: 'Dark', book: PHB },
  { race: 'Elf', subrace: 'Eladrin', book: MTF },
  { race: 'Elf', subrace: 'Sea', book: MTF },
  { race: 'Elf', subrace: 'Shadow', book: MTF },
  { race: 'Gnome', subrace: 'Forest', book: PHB },
  { race: 'Gnome', subrace: 'Rock', book: PHB },
  { race: 'Gnome', subrace: 'Deep', book: SCG },
  { race: 'Halfling', subrace: 'Lightfoot', book: PHB },
  { race: 'Halfling', subrace: 'Stout', book: PHB },
  { race: 'Halfling', subrace: 'Ghostwise', book: SCG },
  { race: 'Elf', subrace: 'Half', book: PHB },
  { race: 'Half Orc', book: PHB },
  { race: 'Human', subrace: 'Standard', book: PHB },
  { race: 'Human', subrace: 'Variant', book: PHB },
  { race: 'Tiefling', subrace: 'Baalzebul', book: PHB },
  { race: 'Tiefling', subrace: 'Dispater', book: PHB },
  { race: 'Tiefling', subrace: 'Fierna', book: PHB },
  { race: 'Tiefling', subrace: 'Glasya', book: PHB },
  { race: 'Tiefling', subrace: 'Levistus', book: PHB },
  { race: 'Tiefling', subrace: 'Mammon', book: PHB },
  { race: 'Tiefling', subrace: 'Mephistopheles', book: PHB },
  { race: 'Tiefling', subrace: 'Zariel', book: PHB },
  { race: 'Tiefling', subrace: 'Variant', book: PHB },
  { race: 'Genasi', subrace: 'Air', book: EE },
  { race: 'Genasi', subrace: 'Earth', book: EE },
  { race: 'Genasi', subrace: 'Fire', book: EE },
  { race: 'Genasi', subrace: 'Water', book: EE },
  { race: 'Goliath', book: EE },
  { race: 'Aasimar', subrace: 'Fallen', book: PHB },
  { race: 'Aasimar', subrace: 'Protector', book: PHB },
  { race: 'Aasimar', subrace: 'Scourge', book: PHB },
  { race: 'Aasimar', subrace: 'Variant', book: PHB },
  { race: 'Bugbear', book: VGM },
  { race: 'Firbolg', book: VGM },
  { race: 'Goblin', book: VGM },
  { race: 'Hobgoblin', book: VGM },
  { race: 'Kenku', book: VGM },
  { race: 'Kobold', book: VGM },
  { race: 'Lizardfolk', book: VGM },
  { race: 'Orc', book: VGM },
  { race: 'Tabaxi', book: VGM },
  { race: 'Triton', book: VGM },
  { race: 'Yuan-ti Pureblood', book: VGM },
  { race: 'Tortle', book: XGE },
  { race: 'Gith', subrace: 'Githyanki', book: MTF },
  { race: 'Gith', subrace: 'Githzerai', book: MTF },
  { race: 'Locathah', book: LOC },
];

export const getRace = () => {
  const { race, subrace, book } = races[getRandomInt(races.length)];
  return {
    race,
    fullRace: `${subrace ? subrace + ' ': ''}${race}`,
    book,
  };
}
